# Build and tag using commit sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/aseem-test-image:${COMMIT_SHA}', '-f', 'Dockerfile']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/aseem-test-image:${COMMIT_SHA}']


#deploy to k8s
- name: "gcr.io/cloud-builders/gke-deploy"
  args:[
  - 'apply'
  - '-f'
  - 'deployment.yaml]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-gke'
